### ISSUE TITLE
Shortcut failure

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#18]
`dice2` _always_ ends up returning `0`

need to investigate

**Comment by martimatix** [comment]
There are couple of ideological and practical issues with this short cut:
- `ScoreSheet` object is now doing functions that have already been established in `Dice`. Rewriting already established functions is a waste of resources.
- From an OOP point of view, it doesn't make sense that the `ScoreSheet` is handling the functions of the dice. At this rate, the only thing `ScoreSheet` is not doing is `roll` and `roll_all`. `Dice` class must remain as an independent and meaningful class.
- I suspect the reason why `dice2` is not behaving as expected is because in `scoresheet.rb` there are two methods defined for `dice2` - one which takes no arguments and another with one argument.
- The name `dice2` is not descriptive. When I woke up this morning and saw that, I thought it had something to do with the second dice in the array.
- If the point of a short cut is to save time, implementation of `dice2` is having the opposite effect if it is causing test failures.
