### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#54]
I want to use this issue for primary communication

**Comment by Zrp200** [comment]
:zzz:

**Comment by martimatix** [comment]
I have chosen to stop working on this project since it has achieved what I initially set out to do. On a personal note, I am doing a Ruby on Rails course next month and therefore turning my attention to Rails for now. Feel free to continue adding to this project but I will be bowing out. Zachary: it has been a pleasure working with you and hope to do more work again with you in the future.

**Comment by Zrp200** [comment]
Me too
